class SEOAgent:
    def generate_meta(self, title):
        """
        दिलेल्या शीर्षकावरून meta-title आणि description तयार करतो
        """
        meta_title = f"{title} - LoanHelpline.co"
        meta_description = f"{title} बद्दल मार्गदर्शन, दर, आणि अर्ज प्रक्रिया. सर्व माहिती मराठीत."
        return {
            "meta_title": meta_title,
            "meta_description": meta_description
        }

    def add_meta_tags(self, html_path):
        """
        HTML फाईलमध्ये SEO meta-tags insert करतो
        """
        try:
            with open(html_path, "r", encoding="utf-8") as f:
                content = f.read()

            title = "आजचे गृहकर्ज दर"
            meta = self.generate_meta(title)

            meta_tags = f"""
<meta name="title" content="{meta['meta_title']}">
<meta name="description" content="{meta['meta_description']}">
<meta name="keywords" content="गृहकर्ज, व्याजदर, बँक दर, Home Loan in Marathi">
<meta name="author" content="LoanBot AI">
"""

            if "<head>" in content:
                content = content.replace("<head>", f"<head>{meta_tags}")
            else:
                # HTML generated by GPT may not have <head>, prepend meta tags
                content = meta_tags + "\n" + content

            with open(html_path, "w", encoding="utf-8") as f:
                f.write(content)

            print(f"✅ SEO meta tags जोडले गेले: {html_path}")

        except Exception as e:
            print(f"❌ SEO meta tag error: {e}")
